# **LEVEL 2**

**1. Form a 1D array containing elements from -2(including) to 10(excluding) in arithmetic progression with common difference 1.5 , negate all elements which are between 2 and 7, in place. Print out this new array.**

In [1]:
import numpy as np
def generate():
    arr = np.arange(-2, 10, 1.5)
    arr[(arr> 2) & (arr < 7)] *= -1
    return arr
generate()

array([-2. , -0.5,  1. , -2.5, -4. , -5.5,  7. ,  8.5])

**2. Create random vector of size 7 and replace the maximum value by 2 and minimum by 7. Sort this array in reverse order. Return the modified vector.**

In [2]:
import numpy as np
def generate():
    random_vector = np.random.random(7)
    random_vector[random_vector.argmax()] = 2
    random_vector[random_vector.argmin()] = 7
    modified_vector = np.array(sorted(random_vector,reverse = True))
    return modified_vector
generate()

array([7.        , 2.        , 0.74860678, 0.71679745, 0.54583489,
       0.35590564, 0.13120769])

**3. Convert a random 7x2 matrix representing cartesian coordinates to polar coordinates. Print out both.**

Hint: use arctan2()

In [3]:
import numpy as np
def generate():
    matrix = np.random.random((7,2))
    row,column = matrix[:,0], matrix[:,1]
    radial_coordinate = np.sqrt(row**2 + column**2)
    angular_coordinate = np.arctan2(column, row)
    print(radial_coordinate)
    print(angular_coordinate) 
    return None
generate()

[0.66809131 0.98304974 1.03258274 0.80852646 0.71894793 1.07031929
 0.92481037]
[0.46391979 0.94723556 0.95907921 1.2192302  1.51491103 0.63391
 1.4068061 ]


**4. Create an numpy array sequence named num_seq when only the starting point, step size and length of sequence is given.**

In [5]:
import numpy as np

length = 15
start = 5
step = 2

def generate(start, length, step):
    end = start + (step*length)
    num_seq = np.arange(start, end, step)
    return num_seq

generate(start, length, step)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

**5. Make a 3*3 array using a 1d array of evenly spaced numbers ranging from 0 to 9, name it arr1.
Then transpose it to obtain arr2. From arr2 subtract a 1*3 array with all elements 1 to get arr4. Return arr4.**

HINT: Use reshape and transpose function.

In [6]:
import numpy as np
def generate():
    arr = np.arange(0,9)                                
    arr1 = arr.reshape(3,3) 
    arr2=arr1.transpose()
    arr3=np.ones(3,dtype=int)
    arr4=arr2-arr3
    return arr4
generate()

array([[-1,  2,  5],
       [ 0,  3,  6],
       [ 1,  4,  7]])

**6. Create a DatetimeIndex that contains each business day of 2016 and use it to index a Series of random numbers. Let's call this Series bus_2k16. Hint: use pd.date_range.**

In [7]:
import pandas as pd
import numpy as np
def generate():
    dti = pd.date_range(start='2016-01-01', end='2016-12-31', freq='B') 
    bus_2k16 = pd.Series(np.random.rand(len(dti)), index=dti)
    print(bus_2k16)
generate()

2016-01-01    0.271555
2016-01-04    0.583283
2016-01-05    0.401136
2016-01-06    0.250179
2016-01-07    0.128566
2016-01-08    0.098462
2016-01-11    0.856489
2016-01-12    0.254759
2016-01-13    0.485466
2016-01-14    0.782258
2016-01-15    0.163734
2016-01-18    0.254019
2016-01-19    0.036039
2016-01-20    0.767556
2016-01-21    0.063107
2016-01-22    0.013342
2016-01-25    0.015829
2016-01-26    0.354130
2016-01-27    0.371966
2016-01-28    0.777087
2016-01-29    0.618626
2016-02-01    0.860232
2016-02-02    0.587397
2016-02-03    0.485359
2016-02-04    0.516719
2016-02-05    0.438297
2016-02-08    0.278900
2016-02-09    0.356606
2016-02-10    0.072066
2016-02-11    0.648117
                ...   
2016-11-21    0.323028
2016-11-22    0.251418
2016-11-23    0.988915
2016-11-24    0.806198
2016-11-25    0.514494
2016-11-28    0.476627
2016-11-29    0.668288
2016-11-30    0.724604
2016-12-01    0.116127
2016-12-02    0.899424
2016-12-05    0.561056
2016-12-06    0.317861
2016-12-07 

**7. For each calendar month in dataframe bus_2k16, from previous problem. Print out the mean of values also find the sum of the values in bus_2k16 for every Monday.**

In [8]:
import pandas as pd
import numpy as np
def generate():
    dti = pd.date_range(start='2016-01-01', end='2016-12-31', freq='B') 
    bus_2k16 = pd.Series(np.random.rand(len(dti)), index=dti)
    print(bus_2k16)
    print(bus_2k16.resample('M').mean())
    print(bus_2k16[bus_2k16.index.weekday == 0].sum())
    return None
generate()

2016-01-01    0.248948
2016-01-04    0.285870
2016-01-05    0.352201
2016-01-06    0.048688
2016-01-07    0.264308
2016-01-08    0.820704
2016-01-11    0.437383
2016-01-12    0.199681
2016-01-13    0.748526
2016-01-14    0.156514
2016-01-15    0.690750
2016-01-18    0.355407
2016-01-19    0.372182
2016-01-20    0.270141
2016-01-21    0.417030
2016-01-22    0.080396
2016-01-25    0.757760
2016-01-26    0.657679
2016-01-27    0.356861
2016-01-28    0.983856
2016-01-29    0.951300
2016-02-01    0.331482
2016-02-02    0.451046
2016-02-03    0.544255
2016-02-04    0.955034
2016-02-05    0.107164
2016-02-08    0.290796
2016-02-09    0.546607
2016-02-10    0.520488
2016-02-11    0.083636
                ...   
2016-11-21    0.811314
2016-11-22    0.710062
2016-11-23    0.641975
2016-11-24    0.069228
2016-11-25    0.073079
2016-11-28    0.155856
2016-11-29    0.968518
2016-11-30    0.732801
2016-12-01    0.466106
2016-12-02    0.693247
2016-12-05    0.996329
2016-12-06    0.222266
2016-12-07 

**8.Given the dataframe df, In the FromTo column split each string on the underscore delimiter to give a new temporary DataFrame with the correct values. Also standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".) Assign the correct column names to this temporary DataFrame named as temp. Return temp.**

In [9]:
import numpy as np
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
import pandas as pd
def generate():
    temp = df.From_To.str.split('_', expand=True)
    temp.columns = ['From', 'To']
    temp['From'] = temp['From'].str.capitalize()
    temp['To'] = temp['To'].str.capitalize()
    return temp
generate()

From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

**9. Given a dataFrame with 10 columns of real numbers. Find that column's label which has the smallest sum? Also count the number of unique rows the dataframe has.**

Hint: use idxmin method.

In [10]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.random(size=(4, 10)), columns=list('qrstuvwxyz'))
def generate():
    print(df.sum().idxmin())
    print(len(df) - df.duplicated(keep=False).sum())
    return None
generate()

z
4


**10. Given a dataFrame df with a column 'int' of integers. Print out the dataframe with filtered out rows which contain the same integer as the row immediately above. Also print out the dataframe after subtracting the mean of all integers from each element.**

Hint: use drop_duplicates and sub methods

In [11]:
import pandas as pd
df = pd.DataFrame({'int': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
def generate():
    print(df.drop_duplicates(subset='int'))
    print(df.sub(df.mean(axis=0), axis=1))
    return None
generate()

   int
0    1
1    2
3    3
4    4
5    5
8    6
9    7
         int
0  -3.272727
1  -2.272727
2  -2.272727
3  -1.272727
4  -0.272727
5   0.727273
6   0.727273
7   0.727273
8   1.727273
9   2.727273
10  2.727273
