# **LEVEL 1 (BASICS)**

**1. Create a null vector of size 7 but the third and last value as 2.**

In [1]:
import numpy as np
def generate():
    vec = np.zeros(7)
    vec[2] = 2
    vec[-1] = 2
    print(vec)
generate()

[0. 0. 2. 0. 0. 0. 2.]


**2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.**

In [2]:
import numpy as np
def generate():
    Vector = np.linspace(0, 2, num = 11, endpoint = True)[ 1:-1 ]
    print(Vector)
generate()

[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


**3. Convert the first character of each element in a series to uppercase?And return the new series. Hint: use map and lambda methods.**

In [4]:
import pandas as pd
series = pd.Series(['life', 'is', 'beautiful. ', 'lets' , 'cherish' ,'the' , 'moment'])
def generate():
    new_series = series.map(lambda x: x[0].upper() + x[1:])
    return new_series
generate()  

0           Life
1             Is
2    Beautiful. 
3           Lets
4        Cherish
5            The
6         Moment
dtype: object

**4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.**

In [5]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
def generate():
    matrix_sub = matrix_fab - matrix_fab.mean(axis = 1, keepdims = True)
    max = matrix_sub.max()
    matrix_norm = matrix_sub/(2*max)
    print(matrix_norm)
generate()

[[-0.5  0.   0.5]
 [-0.5  0.   0.5]
 [-0.5  0.   0.5]]


**5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.**

Hint: use reshape and sorted function.

In [6]:
import numpy as np
def generate():
    rand_vect = np.random.random(12)
    rand_sort = np.array(sorted(rand_vect,reverse=True))
    rand_new = rand_sort.reshape(4,3)
    print(rand_new)
generate()

[[0.98948073 0.96040295 0.79457372]
 [0.76786801 0.65036084 0.58581794]
 [0.41349279 0.3708142  0.26422529]
 [0.25793343 0.25183695 0.16122239]]


**6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.**

In [7]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
def generate():
    df = pd.DataFrame(data, index=labels)
    print(df[df['age'].isnull()])
generate()

   age animal priority  visits
d  NaN    dog      yes       3
h  NaN    cat      yes       1


**7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age**

In [8]:
import pandas as pd
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, index=labels)
def generate():
    df['animal'] = df['animal'].replace('dog', 'Labrador')
    df.loc['d', 'age'] = 2.7  
    mean_age = df.groupby('animal')['age'].mean()
    print(df)
    return mean_age
generate()

   age    animal priority  visits
a  2.5       cat      yes       1
b  3.0       cat      yes       3
c  0.5     snake       no       2
d  2.7  Labrador      yes       3
e  5.0  Labrador       no       2
f  2.0       cat       no       3
g  4.5     snake       no       1
h  NaN       cat      yes       1
i  7.0  Labrador       no       2
j  3.0  Labrador       no       1


animal
Labrador    4.425
cat         2.500
snake       2.500
Name: age, dtype: float64

**8. From the given dataframe get the positions where values of two columns match?**

In [9]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
def generate():
    s = np.where(df.fruit1 == df.fruit2)
    print(s)
    return None
generate()

(array([0, 2, 3, 5, 6, 7], dtype=int64),)


**9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.**

In [10]:
import pandas as pd
import numpy as np
def generate():
    series = pd.Series(np.random.randint(1, 10, 7))
    pos=np.argwhere(series % 4 == 0 )
    print(series)
    print(pos)
generate()

0    5
1    4
2    2
3    5
4    5
5    3
6    4
dtype: int32
[[1]
 [6]]


**10. Stack two given series vertically and horizontally ?**

In [11]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('aanyp'))
def generate():
    verti = series1.append(series2)
    print(verti)
    hori = pd.concat([series1, series2], axis=1)
    print(hori)
    return None
generate()

0    0
1    1
2    2
3    3
4    4
0    a
1    a
2    n
3    y
4    p
dtype: object
   0  1
0  0  a
1  1  a
2  2  n
3  3  y
4  4  p
